### PR TITLE
Restyle of application

### PR DESCRIPTION
**Pull request by Nerdy-Girl**
I've restyled your applications and changed file structure a bit so it's easier to maintain. 
Chat still need to be fixed a bit on mobile though.

### CODE REVIEW

**Comment by Nerdy-Girl** [comment]
@ajaydevarakonda ?

**Comment by ajaydevarakonda** [comment]
Natalie sorry about the delay

**Comment by ajaydevarakonda** [comment]
@CodeMeNatalie sorry about the delay, planning to make some major changes to the application. Will use your styles wherever I can

**Comment by Nerdy-Girl** [comment]
Thank you! Glad I could help :)

**Pull request merged**
